version: '2'
services:
  db:
    image: postgres
    container_name: dratpg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dratpg
      - POSTGRES_PASSWORD=dratpg
  drat: 
    container_name: drat
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db
      
      